repos:
- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0
  hooks:
  - id: mdformat
    args:
      - --number
    additional_dependencies:
      - mdformat-front-matters
      - mdformat-gfm
      - git+https://github.com/p-fruck/mdformat-presenterm@v0.1.0
